services:
  generalsql-db:
    image: postgres
    container_name: remote-Db
    ports:
      - "5448:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=remotedb

volumes:
  postgres_data:
    driver: local